// <auto-generated />
using System;
using AutoImovel.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoImovel.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617014410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoImovel.Shared.Domain.AlocacaoLastro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AporteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAlocacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDesalocacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorAlocado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AporteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("AlocacoesLastro");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Aporte", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SaldoEmLiquidez")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlContratoScp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestidorId");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.FechamentoLucro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlocacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LucroBrutoProporcional")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("LucroLiquidoPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxaGestaoRetida")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxaInfraRetida")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxaPerformanceRetida")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlocacaoId");

                    b.HasIndex("InvestidorId");

                    b.ToTable("FechamentosLucro");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Investidor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Investidores");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AnoFabricacaoModelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("CustosPreparacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Km")
                        .HasColumnType("integer");

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PrecoCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PrecoVendaReal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlLaudoCautelar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.AlocacaoLastro", b =>
                {
                    b.HasOne("AutoImovel.Shared.Domain.Aporte", "Aporte")
                        .WithMany("Alocacoes")
                        .HasForeignKey("AporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoImovel.Shared.Domain.Veiculo", "Veiculo")
                        .WithMany("Alocacoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aporte");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Aporte", b =>
                {
                    b.HasOne("AutoImovel.Shared.Domain.Investidor", "Investidor")
                        .WithMany("Aportes")
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.FechamentoLucro", b =>
                {
                    b.HasOne("AutoImovel.Shared.Domain.AlocacaoLastro", "Alocacao")
                        .WithMany()
                        .HasForeignKey("AlocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoImovel.Shared.Domain.Investidor", "Investidor")
                        .WithMany("FechamentosLucro")
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alocacao");

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Aporte", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Investidor", b =>
                {
                    b.Navigation("Aportes");

                    b.Navigation("FechamentosLucro");
                });

            modelBuilder.Entity("AutoImovel.Shared.Domain.Veiculo", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
